FROM php:8.0-fpm

RUN apt-get update && \
    apt-get install -y \
        zlib1g-dev 

ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN chmod +x /usr/local/bin/install-php-extensions && sync && \
    install-php-extensions mbstring pdo_mysql zip exif pcntl gd


#previous code
# Install dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libpng-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    zip \
    unzip \
    git \
    curl

# RUN docker-php-ext-install pdo pdo_mysql mysqli
# RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli
RUN apt-get install nano -y

RUN curl -sS https://getcomposer.org/installer | php \
    && mv composer.phar /usr/local/bin/composer

# Xdebug
RUN pecl install xdebug \
      && docker-php-ext-enable xdebug

COPY ./xdebug.ini "${PHP_INI_DIR}/conf.d"

EXPOSE 8080 

RUN echo 'post_max_size = 20M' >> /usr/local/etc/php/conf.d/limit.ini
RUN echo 'upload_max_filesize = 20M' >> /usr/local/etc/php/conf.d/limit.ini

RUN echo 'memory_limit = 2024M' >> /usr/local/etc/php/conf.d/docker-php-memlimit.ini
RUN chmod 777 -R /tmp && chmod o+t -R /tmp
